### ISSUE TITLE
Energieeffizienz verbessern (-15%)

### ISSUE THREAD

**Issue by veronikaatzmueller1234** [pcg-platinus/AM-Uebung#22]
Ziel ist es,

1. die derzeitigen Stromkosten (AS-IS = 10kWh/a; ca. 2000€/a: Quelle = letzte Stromabrechnung), um min -15% zu senken. 

Beschreibung:
Einführung eines Smart-Home-Systems mit dem Ziel um die Energieeffizienz zu steigern und eine Einsparung der Energiekosten von ca. 15% zu erreichen. 
Die Ergebnisse sollen über eine App mit übersichtlicher Oberfläche für die Kunden einsehbar sein. 

Acceptance-Criteria: 
1. App mit einfacher Benutzeroberfläche steht zur Verfügung 
- Informationen zum Energieverbrauch sind transparent einsehbar 
- Ergebnis: Jahres-Energieverbrauch hat sich um 15% (auf 8500 KW / a) verringert - Kriterium muss erfüllt sein

**Comment by chris-tipotsch-platinus** [comment]
mit #21 verknüpft weil doppelt. 
Wir geschossen.
